### ISSUE TITLE
runCommand error: system(/usr/local/bin/alertblock /home/simple/blockpush/eac.push) returned 31488

### ISSUE THREAD

**Issue by crackfoo** [simplecrypto/powerpool#125]
Hi, 

I have setup all my coinds to use blocknotify however it seems only a handful actually run the notify script successfully. 

Is there a reason some coinds spit errors when running it?

```
2015-03-12 18:01:37 runCommand error: system(/usr/local/bin/alertblock /home/simple/blockpush/tit.push) returned 31488
2015-03-12 18:01:38 runCommand error: system(/usr/local/bin/alertblock /home/simple/blockpush/pxi.push) returned 31488
2015-03-12 18:01:42 runCommand error: system(/usr/local/bin/alertblock /home/simple/blockpush/eac.push) returned 31488
2015-03-12 18:01:46 runCommand error: system(/usr/local/bin/alertblock /home/simple/blockpush/wdc.push) returned 31488
2015-03-12 18:01:46 runCommand error: system(/usr/local/bin/alertblock /home/simple/blockpush/pxi.push) returned 31488
2015-03-12 18:01:47 runCommand error: system(/usr/local/bin/alertblock /home/simple/blockpush/eac.push) returned 31488
```

I can run it fine from my usr prompt...

**Comment by ericecook** [comment]
If you can run it from command line (and powerpool emits a proper log message) then it isn't really a powerpool issue.

I'm a bit out of my depth here, but FWIW that error message is a system error. Those typically happen from hitting some configured limit, or running out of some resource (memory, available sockets, etc). http://compgroups.net/comp.linux.development.system/system-exit-code/2859965 may be helpful

**Comment by icook** [comment]
You might check the return code you're getting when you run it from command prompt.

Also, when you get junk in the coindaemon logs is it still pushing new block notification? If so, then it's nothing to worry about. Not sure what would be spitting out that code tho, possibly running netcat when it fails to send it's packets?

Either way, I'm going to close this since it's a non-powerpool issue. If you are still having issues feel free to talk about it on the mailing list.

**Comment by crackfoo** [comment]
It works fine when I run it from command line. No return code. There is no more logging of block notification from PUSH, just normal discovery that there is  a new block. If it restart the coind, it returns to sending PUSH successfully for a while, then errors out again...

**Comment by icook** [comment]
What do you mean no return code? Everything you run on shell has a return code, although it is usually 0. After running the push code on command line run `echo $?` to print out the exit code of the last run command.

**Comment by crackfoo** [comment]
Sorry, yeah, I mean it returns success....

**Comment by icook** [comment]
So from a bit of google-fu, exit code 31488 is 123 shifted left 8 bits. This is apparently how most subprocess (like system) handle exit code translation. So that means xargs is giving a 123 exit code, which according to it's man pages means one of the commands it called exited with a non-0 exit code. This is honestly quite common, since if your push script times out when trying to push the packet (ie powerpool isn't running or something) then it will return a non-zero.

I would triple check that when you see this error in the coindaemon logs you confirm that:

1. Powerpool was indeed running
2. It was listening on the UDP port specified in your push script
3. It didn't mention recieving any kind of RPC command

**Comment by crackfoo** [comment]
Still trying to track this issue down. The syntax for the push script are all the same and the work. They will work fine for a period of time... then start give out that error for no apparent reason. PP is running and at the same time accepting other PUSH notifications. Is there an alternative to using netcat? Not sure what else to try here. I've tried jacking up the ulimits on the user's and no change.

**Comment by crackfoo** [comment]
I found the issue was related to the use of nc. I changed the alert block script to use ncat and have not seen a failure yet and my orphan rate has dropped significantly.

**Comment by icook** [comment]
Glad to hear that you solved this, congrats on sticking with it.

I've opened the above ticket to remind me to add it to the docs.
